# Goal - 固体投料-小瓶  
string assign_material_name         # 固体名称_粉末加样模块-投料  
string material_id                # 固体投料类型_粉末加样模块-投料
string time                      # 观察时间_反应模块-观察搅拌结果
string torque_variation           #是否观察1否2是_反应模块-观察搅拌结果    
---
# Result - 操作结果  
string return_info                    # 结果消息
---
# Feedback - 实时反馈  
