# Goal - 液体投料-小瓶非滴定操作参数
string volume_formula           # 投料体积公式
string assign_material_name     # 溶剂名称
string titration_type          # 滴定类型1否2是
string time                    # 观察时间（单位min）
string torque_variation        # 是否观察1否2是
string temperature             # 温度设置
---
# Result - 操作结果
bool success                   # 操作是否成功
string return_info             # 结果消息
int32 code                     # 操作结果代码（1表示成功，0表示失败）
---
# Feedback - 实时反馈
string feedback                # 操作过程中的反馈信息