package:
  name: unilabos
  version: "0.10.5"

source:
  path: ../..

build:
  noarch: python
  script: |
    {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
#    {{ PYTHON }} clean_build_dir.py

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - unilabos
