package:
  name: ros-humble-unilabos-msgs
  version: 0.10.5
source:
  path: ../../unilabos_msgs
  target_directory: src

build:
  script:
  - if: win
    then:
    - copy %RECIPE_DIR%\bld_ament_cmake.bat %SRC_DIR%
    - call %SRC_DIR%\bld_ament_cmake.bat
  - if: unix
    then:
    - cp $RECIPE_DIR/build_ament_cmake.sh $SRC_DIR
    - bash $SRC_DIR/build_ament_cmake.sh

about:
  repository: https://github.com/dptech-corp/Uni-Lab-OS
  license: BSD-3-Clause
  description: "ros-humble-unilabos-msgs is a package that provides message definitions for Uni-Lab-OS."

requirements:
  build:
  - ${{ compiler('cxx') }}
  - ${{ compiler('c') }}
  - python ==3.11.11
  - numpy
  - if: build_platform != target_platform
    then:
    - pkg-config
    - cross-python_${{ target_platform }}
  - if: linux and x86_64
    then:
    - sysroot_linux-64 ==2.17
  - ninja
  - setuptools
  - cython
  - cmake
  - if: unix
    then:
    - make
    - coreutils
  - if: osx
    then:
    - tapi
  - if: win
    then:
    - vs2022_win-64
  host:
  - numpy
  - pip
  - if: build_platform == target_platform
    then:
    - pkg-config
  - robostack-staging::ros-humble-action-msgs
  - robostack-staging::ros-humble-ament-cmake
  - robostack-staging::ros-humble-ament-lint-auto
  - robostack-staging::ros-humble-ament-lint-common
  - robostack-staging::ros-humble-ros-environment
  - robostack-staging::ros-humble-ros-workspace
  - robostack-staging::ros-humble-rosidl-default-generators
  - robostack-staging::ros-humble-std-msgs
  - robostack-staging::ros-humble-geometry-msgs
  - robostack-staging::ros2-distro-mutex=0.6
  run:
  - robostack-staging::ros-humble-action-msgs
  - robostack-staging::ros-humble-ros-workspace
  - robostack-staging::ros-humble-rosidl-default-runtime
  - robostack-staging::ros-humble-std-msgs
  - robostack-staging::ros-humble-geometry-msgs
  - robostack-staging::ros2-distro-mutex=0.6
  - if: osx and x86_64
    then:
    - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
