package:
  name: unilabos
  version: 0.10.6

source:
  path: ../unilabos
  target_directory: unilabos

build:
  python:
    entry_points:
     - unilab = unilabos.app.main:main
  script:
  - set PIP_NO_INDEX=
  - if: win
    then:
    - copy %RECIPE_DIR%\..\MANIFEST.in %SRC_DIR%
    - copy %RECIPE_DIR%\..\setup.cfg %SRC_DIR%
    - copy %RECIPE_DIR%\..\setup.py %SRC_DIR%
    - call %PYTHON% -m pip install %SRC_DIR%
  - if: unix
    then:
    - cp $RECIPE_DIR/../MANIFEST.in $SRC_DIR
    - cp $RECIPE_DIR/../setup.cfg $SRC_DIR
    - cp $RECIPE_DIR/../setup.py $SRC_DIR
    - $PYTHON -m pip install $SRC_DIR


requirements:
  host:
  - python ==3.11.11
  - pip
  - setuptools
  - zstd
  - zstandard
  run:
  - conda-forge::python ==3.11.11
  - compilers
  - cmake
  - zstd
  - zstandard
  - ninja
  - if: unix
    then:
    - make
  - sphinx
  - sphinx_rtd_theme
  - numpy
  - scipy
  - pandas
  - networkx
  - matplotlib
  - pint
  - pyserial
  - pyusb
  - pylibftdi
  - pymodbus
  - python-can
  - pyvisa
  - opencv
  - pydantic
  - fastapi
  - uvicorn
  - gradio
  - flask
  - websockets
  - ipython
  - jupyter
  - jupyros
  - colcon-common-extensions
  - robostack-staging::ros-humble-desktop-full
  - robostack-staging::ros-humble-control-msgs
  - robostack-staging::ros-humble-sensor-msgs
  - robostack-staging::ros-humble-trajectory-msgs
  - ros-humble-navigation2
  - ros-humble-ros2-control
  - ros-humble-robot-state-publisher
  - ros-humble-joint-state-publisher
  - ros-humble-rosbridge-server
  - ros-humble-cv-bridge
  - ros-humble-tf2
  - ros-humble-moveit
  - ros-humble-moveit-servo
  - ros-humble-simulation
  - ros-humble-tf-transformations
  - transforms3d
  - uni-lab::ros-humble-unilabos-msgs

about:
  repository: https://github.com/dptech-corp/Uni-Lab-OS
  license: GPL-3.0-only
  description: "Uni-Lab-OS"
